In [1]:
using PyPlot;
coinFlip(w)= (rand()< w)? 1: 0;

In [30]:
num=0; w= 0.25;

H= [0:0.001:1];
    
    events= zeros(Int,1,num);
    for i=1:num
        events[i]= coinFlip(w);
    end
        
    perior_prob= zeros(3,length(H));
    posterior_prob= zeros(3,length(H));
    norm= zeros(3,2);
    posterior_probNorm= zeros(3,length(H));
    
    #--------------------------------------
    b=1; a=0; #parameters for Uniform distribution
    
    segma= 0.5; meue= 0.5;#parameters for Normal distribution
    
    alfa= 0.5; beta=0.5;#parameters for Beta distribution
    
    N= num; R= sum(events);#parameters for Binomial distribution
    #--------------------------------------------------
    if num > 0
        likelihood= H.^R .* (1-H).^(N-R); #likelihood function follows Binomial Distribution
    else
        likelihood= 1;  #in at first step no data
    end
        
    perior_prob[1,:]= (1/(b-a))*ones(Int,1,length(H)); #perior function follows Uniform distribution
    for i=1:length(H)
        perior_prob[2,i]= (exp(-(H[i]-meue)^2 / (2*segma^2))/(segma*(2* pi)^(1/2)));
        perior_prob[3,i]= (H[i])^(alfa-1)*(1-H[i])^(beta-1);
    end

    posterior_prob= likelihood' .* perior_prob;
    posterior_probNorm= posterior_prob;

In [34]:
norm= [minimum(posterior_prob,2) maximum(posterior_prob,2)];
        println("Hellow in normalization")
        println(norm)
    
        if (norm[3,2] == Inf)
            k= find(posterior_prob[3,:] .== Inf);
        println("K numbers -------  ",k)
    println("posterior_prob[3,k] ------- \n ",posterior_prob[3,k])
            posterior_prob[3,k] = 1;
    println("posterior_prob[3,k]------- \n ",posterior_prob[3,k])
            norm[3,2]= 1;
            sec_max= maximum(posterior_prob[3,:])
    println("Sec max -------  ", sec_max)
            posterior_prob[3,k] = sec_max + 1;
            norm[3,2]= sec_max+ 1;
        end

        for j=2:3
            posterior_probNorm[j,:] = (posterior_prob[j,:] - norm[j,1])./(norm[j,2] - norm[j,1]);
        end 

Hellow in normalization
[1.0 1.0
 0.0 1.0
 0.0 1.0]


In [29]:
xx=[2 5 6;2 6 9];
find(xx[2,:] .== 9)

1-element Array{Int64,1}:
 3

In [11]:
println("Posterior prob 3 \n", posterior_prob[3,:])

Posterior prob 3 
[NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN N

In [12]:
likelihood

1

In [13]:
perior_prob[1,:]

1x1001 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [17]:
likelihood' .* perior_prob

3x1001 Array{Float64,2}:
   1.0        1.0        1.0       …   1.0        1.0         1.0     
   0.483941   0.484909   0.485877      0.485877   0.484909    0.483941
 Inf         31.6386    22.3831       22.3831    31.6386    Inf       